# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('tweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('tweets', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_handle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tweets',
            name='twitter_handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Users'),
        ),
    ]
